STATION_AMOUNT = 3
ADMIN_TABLE_ROWS = 33
ADMIN_TABLE_COLUMNS = 3
STATION_DATA_FILE_COLUMNS = ["Measurement start time",
                             "Measurement end time",
                             "Reactive power phase A on",
                             "Reactive power phase B on",
                             "Reactive power phase C on",
                             "Active power phase A on",
                             "Active power phase B on",
                             "Active power phase C on",
                             "Voltage phase A on",
                             "Voltage phase B on",
                             "Voltage phase C on",
                             "Cosine phase A on",
                             "Cosine phase B on",
                             "Cosine phase C on",
                             "Reactive power phase A off",
                             "Reactive power phase B off",
                             "Reactive power phase C off",
                             "Active power phase A off",
                             "Active power phase B off",
                             "Active power phase C off",
                             "Voltage phase A off",
                             "Voltage phase B off",
                             "Voltage phase C off",
                             "Cosine phase A off",
                             "Cosine phase B off",
                             "Cosine phase C off",
                             "Number of powered blocks"]
