DATA_FOLD = "lib"
OUT_FOLD = "out"
TMP_FOLD = "tmp"

DATA_BACKGROUND_PATH = f"{DATA_FOLD}/img/login-background.jpg"
RESIZED_BACKGROUND_PATH = f"{TMP_FOLD}/resized-background.jpg"
STATION_DATA_FOLD = f"{DATA_FOLD}/example"
ADMIN_DATA_FILE_PATH = f"{DATA_FOLD}/admin-data.csv"
USER_DATA_FILE_PATH = f"{DATA_FOLD}/user-data.csv"
CUR_LOGIN_DATA_PATH = f"{TMP_FOLD}/login-data.csv"
PLOT_TABLE_PATH = f"{TMP_FOLD}/plot-table.csv"
OUT_TABLE_PATH = f"{OUT_FOLD}/table.csv"
OUT_PICT1_PATH = f"{OUT_FOLD}/1.png"
OUT_PICT2_PATH = f"{OUT_FOLD}/2.png"
