# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file "AdminWindow.ui"
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtWidgets


class Ui_AdminWindow(object):

    def setupUi(self, AdminWindow):
        global k
        global _translate
        AdminWindow.setObjectName("AdminWindow")
        AdminWindow.resize(510, 580)
        self.pushButton = QtWidgets.QPushButton(AdminWindow)
        self.pushButton.setGeometry(QtCore.QRect(10, 20, 181, 61))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(AdminWindow)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 100, 181, 61))
        self.pushButton_2.setObjectName("pushButton_2")

        self.label = QtWidgets.QLabel(AdminWindow)
        self.label.setGeometry(QtCore.QRect(270, 30, 101, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(AdminWindow)
        self.label_2.setGeometry(QtCore.QRect(270, 80, 111, 21))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(AdminWindow)
        self.lineEdit.setGeometry(QtCore.QRect(270, 50, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(AdminWindow)
        self.lineEdit_2.setGeometry(QtCore.QRect(270, 110, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(AdminWindow)
        self.lineEdit_3.setEnabled(True)
        self.lineEdit_3.setGeometry(QtCore.QRect(270, 180, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_3 = QtWidgets.QLabel(AdminWindow)
        self.label_3.setGeometry(QtCore.QRect(270, 150, 171, 16))
        self.label_3.setObjectName("label_3")
        self.tableWidget = QtWidgets.QTableWidget(AdminWindow)
        self.tableWidget.setGeometry(QtCore.QRect(10, 231, 481, 331))
        self.tableWidget.setMaximumSize(QtCore.QSize(481, 331))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(33)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(31, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(32, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 2, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.pushButton_3 = QtWidgets.QPushButton(AdminWindow)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 170, 181, 41))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(AdminWindow)
        QtCore.QMetaObject.connectSlotsByName(AdminWindow)
        self.pushButton_3.clicked.connect(self.saveQuit)

    def retranslateUi(self, AdminWindow):
        _translate = QtCore.QCoreApplication.translate
        AdminWindow.setWindowTitle(_translate("AdminWindow", "Form"))
        self.pushButton.setText(_translate("AdminWindow", "Добавить Администратора"))
        self.pushButton_2.setText(_translate("AdminWindow", "Добавить пользователя"))
        self.label.setText(_translate("AdminWindow", "Логин:"))
        self.label_2.setText(_translate("AdminWindow", "Пароль:"))
        self.label_3.setText(_translate("AdminWindow", "Серийные номера пользователя"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("AdminWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("AdminWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("AdminWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("AdminWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("AdminWindow", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("AdminWindow", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("AdminWindow", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("AdminWindow", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("AdminWindow", "9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("AdminWindow", "10"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("AdminWindow", "11"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("AdminWindow", "12"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("AdminWindow", "13"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("AdminWindow", "14"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("AdminWindow", "15"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("AdminWindow", "16"))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("AdminWindow", "17"))
        item = self.tableWidget.verticalHeaderItem(17)
        item.setText(_translate("AdminWindow", "18"))
        item = self.tableWidget.verticalHeaderItem(18)
        item.setText(_translate("AdminWindow", "19"))
        item = self.tableWidget.verticalHeaderItem(19)
        item.setText(_translate("AdminWindow", "20"))
        item = self.tableWidget.verticalHeaderItem(20)
        item.setText(_translate("AdminWindow", "21"))
        item = self.tableWidget.verticalHeaderItem(21)
        item.setText(_translate("AdminWindow", "22"))
        item = self.tableWidget.verticalHeaderItem(22)
        item.setText(_translate("AdminWindow", "23"))
        item = self.tableWidget.verticalHeaderItem(23)
        item.setText(_translate("AdminWindow", "25"))
        item = self.tableWidget.verticalHeaderItem(24)
        item.setText(_translate("AdminWindow", "26"))
        item = self.tableWidget.verticalHeaderItem(25)
        item.setText(_translate("AdminWindow", "27"))
        item = self.tableWidget.verticalHeaderItem(26)
        item.setText(_translate("AdminWindow", "28"))
        item = self.tableWidget.verticalHeaderItem(27)
        item.setText(_translate("AdminWindow", "29"))
        item = self.tableWidget.verticalHeaderItem(28)
        item.setText(_translate("AdminWindow", "30"))
        item = self.tableWidget.verticalHeaderItem(29)
        item.setText(_translate("AdminWindow", "31"))
        item = self.tableWidget.verticalHeaderItem(30)
        item.setText(_translate("AdminWindow", "32"))
        item = self.tableWidget.verticalHeaderItem(31)
        item.setText(_translate("AdminWindow", "33"))
        item = self.tableWidget.verticalHeaderItem(32)
        item.setText(_translate("AdminWindow", "35"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("AdminWindow", "Логин"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("AdminWindow", "Пароль"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("AdminWindow", "Номера"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_3.setText(_translate("AdminWindow", "Сохранить изменения и выйти"))

        row = 0
        login_data = open("lib/user-data.txt")

        for line in login_data:
            if len(line) > 2:
                login, password, numbers = line.split()

                print(login, password, numbers)

                item = self.tableWidget.item(row, 0)
                item.setText(_translate("AdminWindow", str(login)))
                item = self.tableWidget.item(row, 1)
                item.setText(_translate("AdminWindow", str(password)))
                item = self.tableWidget.item(row, 2)
                item.setText(_translate("AdminWindow", str(numbers)))

                row += 1

        login_data.close()

    def saveQuit(self):
        login_data = open("lib/user-data.txt", "w")
        login_data.close()
        login_data = open("lib/user-data.txt", "a+")

        for row in range(7):
            login = self.tableWidget.item(row, 0).text()
            password = self.tableWidget.item(row, 1).text()
            numbers = self.tableWidget.item(row, 2).text()

            print(login, password, numbers)

            if len(login) > 2:
                login_data.write(f"{login} {password} {numbers}\n")

        login_data.close()
